#define kSwitchDuration 2
#define kAppearDelay 1.5
#define kBgImageCount 8
#define kDiaryImageCount 16
#define kExpressionImageCount 35

#define kBgImage @"BgImage"
#define kDiaryImage @"DiaryImage"
#define kBgNumber @"BgNumber"
#define kDiaryNumber @"DiaryNumber" 
#define kWelcomeView @"WelcomeView"
#define kGestureTip @"GestureTip"
#define kPaperAlpha @"PaperAlpha"
#define kPlan @"Plan"
#define kPlanName @"PlanName"
#define kUser @"User"
#define kUserName @"UserName"
#define kSavedNumber @"SavedNumber"
#define kSavedDate @"SavedDate"
#define kExpressionImage @"ExpressionImage"
#define kDiaryDescriber @"DiaryDescriber"
#define kLastContent1 @"LastContent1"
#define kLastContent2 @"LastContent2"
#define kLastContent3 @"LastContent3"
#define kLastContent4 @"LastContent4"
#define kLastContent5 @"LastContent5"
#define kLastContent6 @"LastContent6"
#define kLastContent7 @"LastContent7"
#define kLastContent8 @"LastContent8"
#define kLastPlace @"LastPlace"
#define kContentColor @"ContentColor"
#define kTitleColor @"TitleColor"